apiVersion: v1
kind: Service
metadata:
  name: visitor-app
spec:
  type: NodePort
  selector:
    app: visitor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

